### ISSUE TITLE
Support to Erlang 17.0

### ISSUE THREAD

**Issue by edgurgel** [archaelus/heroku-buildpack-erlang#12]
Is there any?

**Comment by edgurgel** [comment]
I saw that https://s3.amazonaws.com/heroku-buildpack-erlang/OTP-17.0.tgz exists, so we need to use "OTP-" instead of "OTP_" as was used for previous versions?

**Comment by archaelus** [comment]
The tarball names (which are the names you need to put in .preferred_otp_version) are the same as the release tag names in the erlang/otp repo. The tag name scheme did change with the 17.0 release (the release is not R17 as it would have been previously).

**Comment by edgurgel** [comment]
Got it! Thanks!
